#!/usr/bin/env python3
"""Generate the Cordis patch overlay that loads the SIGA plugin.

The harness requires plugin module paths in a patch to be **absolute**: a patch
contributes configuration but does not move the profile directory the loader
resolves module specifiers from. Rather than committing a machine-specific
absolute path, this script writes the overlay from the checkout's real location.

Generated file: ``harness/siga-patch.yml`` (git-ignored).

Usage::

    python harness/make_patch.py            # write the patch
    python harness/make_patch.py --print    # write nothing, show the content

Then start a harness with it::

    cd /path/to/deepseek-harness
    pnpm dsh web --patch /path/to/SIGA-LAMMPS/harness/siga-patch.yml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_ENTRY = REPO_ROOT / "harness" / "siga-plugin" / "src" / "index.ts"
OUTPUT = REPO_ROOT / "harness" / "siga-patch.yml"

TEMPLATE = """\
# GENERATED by harness/make_patch.py — do not edit, and do not commit.
#
# A Cordis patch overlay that inserts the SIGA-LAMMPS plugin and mounts the
# adapter's MCP server into an existing profile. Absolute paths are mandatory
# here: a patch contributes configuration but does not change the profile
# directory from which module specifiers resolve.
#
#   pnpm dsh web --patch {patch_path}
#
# Every entry is an effect that unwinds when the plugin unloads, so the everyday
# `web` profile is untouched once this overlay is not passed.

- insert:
    # M and S live in-process: prompt sections and turn listeners have no
    # out-of-process equivalent.
    - id: siga-lammps
      name: '{entry}'
      config:
        # Active benchmark task id, surfaced to the primer as {{{{siga_task}}}}.
        # Left unset for interactive use; the benchmark driver sets it per run.
        activeTask: {active_task}
        pythonBin: '{python_bin}'
        taskId: {task_id}

    # R and X live behind MCP, so the adapter stays a separate Python process and
    # the harness learns nothing about LAMMPS. The tools reach the model as
    # mcp__lammps__search_lammps and mcp__lammps__validate_lammps_input.
    - id: siga-lammps-mcp
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: lammps
        transport: stdio
        command: '{python_bin}'
        args: ['-m', 'adapter.mcp_server']
        cwd: '{repo_root}'
        # Validation reads a workspace and retrieval reads a local index; both
        # are fast, but a first-run index build is not. This bounds a wedged
        # adapter rather than killing it mid-write.
        toolCallTimeoutMs: 120000
"""


def render(active_task: str | None = None, task_id: str | None = None) -> str:
    venv_python = REPO_ROOT / ".venv" / "bin" / "python"
    return TEMPLATE.format(
        patch_path=OUTPUT,
        entry=PLUGIN_ENTRY,
        repo_root=REPO_ROOT,
        python_bin=venv_python,
        active_task=f"'{active_task}'" if active_task else "''",
        task_id=f"'{task_id}'" if task_id else "''",
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--print", dest="print_only", action="store_true", help="print instead of writing")
    parser.add_argument("--active-task", default=None, help="benchmark task id to bind for the agent")
    parser.add_argument(
        "--task-id",
        default=None,
        help="benchmark task id the stop gate validates against (usually the same as --active-task)",
    )
    args = parser.parse_args(argv)

    if not PLUGIN_ENTRY.is_file():
        print(f"error: plugin entry not found: {PLUGIN_ENTRY}", file=sys.stderr)
        return 1

    task_id = args.task_id or args.active_task
    content = render(args.active_task, task_id)
    if args.print_only:
        print(content, end="")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    print(f"  plugin entry : {PLUGIN_ENTRY}")
    print(f"  mcp server   : python -m adapter.mcp_server  (cwd {REPO_ROOT})")
    if task_id:
        print(f"  bound task   : {task_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
