#!/usr/bin/env python3
"""Generate the Cordis patch overlay that loads the SIGA plugin.

The harness requires plugin module paths in a patch to be **absolute**: a patch
contributes configuration but does not move the profile directory the loader
resolves module specifiers from. Rather than committing a machine-specific
absolute path, this script writes the overlay from the checkout's real location.

Generated file: ``harness/siga-patch.yml`` (git-ignored).

Usage::

    python harness/make_patch.py            # write the patch
    python harness/make_patch.py --print    # write nothing, show the content

Then start a harness with it::

    cd /path/to/deepseek-harness
    pnpm dsh web --patch /path/to/SIGA-LAMMPS/harness/siga-patch.yml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_ENTRY = REPO_ROOT / "harness" / "siga-plugin" / "src" / "index.ts"
OUTPUT = REPO_ROOT / "harness" / "siga-patch.yml"

TEMPLATE = """\
# GENERATED by harness/make_patch.py — do not edit, and do not commit.
#
# A Cordis patch overlay that configures the agent-preset roster only.
#
# It deliberately mounts NO adapter components. The four ablation configurations
# live in harness/presets/<id>/agent.cordis.yml, because a preset decides the
# tools and prompt sections one session sees while a sibling preset's stay deaf.
# Mounting the plugin here instead would apply it to every session, including
# vanilla, and the ablation would silently compare a configuration against
# itself — which is exactly what an earlier version of this file did.
#
#   pnpm dsh web --patch {patch_path}          # interactive, default preset
#
# Absolute paths are mandatory: a patch contributes configuration but does not
# change the profile directory from which module specifiers resolve.

# INSERTED, not patched. A patch can only modify a row that exists, and the
# roster is mounted by the web-app bundle — the headless profile stacks only
# dsh-base and dsh-headless, so patching by id fails with "entry not found" and
# every session then runs with no preset at all. Inserting works for both
# profiles, and the benchmark needs headless specifically.
- id: webserver
  config:
    host: 127.0.0.1
    port: {web_port}

- insert:
{component_rows}
    - id: agent-presets
      name: '@deepseek-ai/dsh-agent-presets'
      config:
        # Which configuration a session runs when it names none. The benchmark
        # driver overrides this per run; interactive use gets what is set here.
        default: {default_preset}
        # `trust: system` matches the shipped root, because these compositions
        # are versioned with the project rather than authored by a person.
        roots:
          - path: '{presets_dir}'
            trust: system
"""

COMPONENT_ROWS = """\
    - id: siga-memory
      name: '{entry}'
      config:
        memoryPath: ''
        maxChars: 8000
        activeTask: {active_task}
        pythonBin: '{python_bin}'
        stopGate: {stop_gate}
        taskId: {task_id}

    - id: siga-mcp
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: lammps
        transport: stdio
        command: '{python_bin}'
        args: ['-m', 'adapter.mcp_server']
        cwd: '{repo_root}'
        toolCallTimeoutMs: 120000
"""


def component_rows(
    preset: str,
    active_task: str | None,
    task_id: str | None,
) -> str:
    """The plugin rows one ablation configuration mounts.

    Empty for vanilla. M alone adds only the in-process plugin; R and X arrive
    through the MCP client, and S is a config flag on the same plugin so M cannot
    drift between the configurations that include it.
    """
    if preset == "vanilla":
        return ""
    rows = COMPONENT_ROWS.format(
        entry=PLUGIN_ENTRY,
        python_bin=REPO_ROOT / ".venv" / "bin" / "python",
        repo_root=REPO_ROOT,
        active_task=f"'{active_task}'" if active_task else "''",
        task_id=f"'{task_id}'" if task_id else "''",
        stop_gate="true" if preset == "mrsx" else "false",
    )
    if preset == "m":
        # Strip the MCP block, leaving procedural memory only.
        rows = rows.split("    - id: siga-mcp")[0]
    return rows


def render(
    active_task: str | None = None,
    task_id: str | None = None,
    default_preset: str = "vanilla",
    web_port: int = 3081,
    profile: str = "headless",
) -> str:
    venv_python = REPO_ROOT / ".venv" / "bin" / "python"
    overlay = TEMPLATE.format(
        patch_path=OUTPUT,
        entry=PLUGIN_ENTRY,
        repo_root=REPO_ROOT,
        python_bin=venv_python,
        active_task=f"'{active_task}'" if active_task else "''",
        task_id=f"'{task_id}'" if task_id else "''",
        default_preset=default_preset,
        presets_dir=PRESETS_DIR,
        component_rows=component_rows(default_preset, active_task, task_id),
        web_port=web_port,
    )
    return _roster_form(overlay, profile)


def _roster_form(overlay: str, profile: str) -> str:
    """Adapt the overlay's roster row to the profile it targets.

    The two profiles need genuinely different forms, and both failures are loud
    rather than silent:

    * **headless** stacks only dsh-base and dsh-headless, and neither
      contributes a roster row, so the overlay must INSERT one. Patching by id
      fails with 'entry "agent-presets" not found'.
    * **web** already mounts a roster through the web-app bundle, so inserting
      collides with 'duplicate loader entry id: agent-presets'. It must be
      patched instead.

    Unwrapping the insert block is expressed as a transform of the rendered
    overlay rather than a second template, so the two forms cannot drift apart.
    """
    if profile != "web":
        return overlay
    # Unwrap the insert block, since the web-app bundle already mounts a roster
    # and inserting a second one is a duplicate-id error.
    lines = overlay.split("\n")
    unwrapped: list[str] = []
    unwrapping = False
    for line in lines:
        if line.strip() == "- insert:":
            unwrapping = True
            continue
        if unwrapping:
            if line.startswith("    "):
                unwrapped.append(line[4:])
                continue
            if line.strip() == "":
                unwrapped.append(line)
                continue
            unwrapping = False
        unwrapped.append(line)

    # Then drop the roster row entirely. It does not work here: the web roster
    # resolves the harness's own shipped presets and ignores our roots, so both
    # an explicit `agentPreset` and the row's own `default` name a preset that
    # cannot be found and every session creation fails. The web overlay does not
    # need presets anyway — it mounts the configuration's components directly,
    # which is the mechanism already proven to work. Keeping a row that can only
    # fail would be worse than having none.
    out: list[str] = []
    skipping = False
    for line in unwrapped:
        if line.startswith("- id: agent-presets"):
            skipping = True
            continue
        if skipping:
            if line.startswith(("  ", "\t")) or line.strip() == "":
                continue
            skipping = False
        out.append(line)
    text = "\n".join(out)
    while "\n\n\n" in text:
        text = text.replace("\n\n\n", "\n\n")
    return text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--print", dest="print_only", action="store_true", help="print instead of writing")
    parser.add_argument("--active-task", default=None, help="benchmark task id to bind for the agent")
    parser.add_argument("--port", type=int, default=3081, help="web server port")
    parser.add_argument(
        "--mode",
        choices=("headless", "web"),
        default="headless",
        help="target profile; the roster row must be inserted for headless and patched for web",
    )
    parser.add_argument(
        "--preset",
        default="vanilla",
        choices=sorted(PRESET_SUMMARIES),
        help="which ablation configuration a session runs by default",
    )
    parser.add_argument(
        "--task-id",
        default=None,
        help="benchmark task id the stop gate validates against (usually the same as --active-task)",
    )
    args = parser.parse_args(argv)

    if not PLUGIN_ENTRY.is_file():
        print(f"error: plugin entry not found: {PLUGIN_ENTRY}", file=sys.stderr)
        return 1

    task_id = args.task_id or args.active_task
    presets = write_presets()
    content = render(args.active_task, task_id, args.preset, args.port, args.mode)
    if args.print_only:
        print(content, end="")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    print(f"  plugin entry : {PLUGIN_ENTRY}")
    print(f"  mcp server   : python -m adapter.mcp_server  (cwd {REPO_ROOT})")
    print(f"  presets      : {', '.join(presets)}  (default {args.preset})")
    if task_id:
        print(f"  bound task   : {task_id}")
    return 0



# --------------------------------------------------------------------------- #
# agent presets — the ablation
# --------------------------------------------------------------------------- #
#
# The four configurations differ ONLY in which adapter components are mounted.
# Putting them in presets rather than in the profile patch is what makes that
# true: a preset decides the tools and prompt sections one session sees, and a
# sibling preset's listeners stay deaf to it. Everything else — model, harness,
# inference settings, task text — is held constant by the driver.
#
# M and S come from the in-process plugin; R and X come from the MCP server. The
# four rows are therefore a genuine factorial: M alone, M+R, and M+R+X+S.

PRESETS_DIR = REPO_ROOT / "harness" / "presets"

PRESET_HEADER = """\
# GENERATED by harness/make_patch.py — do not edit, and do not commit.
#
# Preset: {preset}
# {summary}
#
# A preset is a per-session composition: the tools and prompt sections listed
# here are exactly what a session on this preset sees. That is what makes the
# ablation admissible, since the adapter configuration becomes the only variable.
"""

PRESET_SUMMARIES = {
    "vanilla": "No adapter components. The capability floor.",
    "m": "M only: always-on procedural memory, no retrieval, no validation.",
    "mr": "M + R: procedural memory and retrieval, but nothing is validated.",
    "mrsx": "M + R + X + S: the full adapter, including the enforced stop gate.",
}


def render_preset(preset: str) -> str:
    """Render one preset's composition."""
    venv_python = REPO_ROOT / ".venv" / "bin" / "python"
    plugin = PLUGIN_ENTRY
    lines = [PRESET_HEADER.format(preset=preset, summary=PRESET_SUMMARIES[preset])]

    if preset == "vanilla":
        # Deliberately empty: a vanilla session gets the harness's own tools and
        # nothing from the adapter.
        lines.append("[]\n")
        return "\n".join(lines)

    lines.append("- id: siga-memory")
    lines.append(f"  name: '{plugin}'")
    lines.append("  config:")
    lines.append("    memoryPath: ''")
    lines.append("    maxChars: 8000")
    lines.append("    activeTask: ''")
    lines.append(f"    pythonBin: '{venv_python}'")
    # S is enabled only in the full configuration. Keeping it a config flag on
    # one plugin rather than two plugins means M cannot drift between the
    # configurations that include it.
    lines.append(f"    stopGate: {'true' if preset == 'mrsx' else 'false'}")
    lines.append("    taskId: ''")
    lines.append("")

    if preset in ("mr", "mrsx"):
        lines.append("- id: siga-mcp")
        lines.append("  name: '@deepseek-ai/dsh-mcp-client'")
        lines.append("  config:")
        lines.append("    serverName: lammps")
        lines.append("    transport: stdio")
        lines.append(f"    command: '{venv_python}'")
        lines.append("    args: ['-m', 'adapter.mcp_server']")
        lines.append(f"    cwd: '{REPO_ROOT}'")
        lines.append("    toolCallTimeoutMs: 120000")
        lines.append("")

    return "\n".join(lines)


def write_presets() -> list[str]:
    """Write every preset directory, returning the ids written."""
    written: list[str] = []
    for preset in PRESET_SUMMARIES:
        directory = PRESETS_DIR / preset
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "agent.cordis.yml").write_text(render_preset(preset), encoding="utf-8")
        written.append(preset)
    return written

if __name__ == "__main__":
    raise SystemExit(main())
